---
title: "R Notebook"
output: html_notebook
---

# Tensor / Cheybshev

Tensoring volatility calibration Calibration of the rough Bergomi volatility model via Chebyshev Tensors

Chebyshev Greeks Smoothing Gamma without Bias

+ https://arxiv.org/pdf/2106.12431.pdf
+ https://www.bayes.city.ac.uk/__data/assets/pdf_file/0005/647069/Scoleri-Chebyshev-Greeks.pdf

Chebyshev Methods for Ultra-efficient Risk Calculations

+ https://arxiv.org/abs/1805.00898

Tensoring volatility calibration
+ https://arxiv.org/abs/2012.07440

Application of Quasi Monte Carlo and Global Sensitivity Analysis to Option Pricing and Greeks: Finite Differences vs. AAD
+ https://onlinelibrary.wiley.com/doi/abs/10.1002/wilm.10972
+ https://www.broda.co.uk/gsa/Pricing%20and%20Hedging%20Multi-Asset%20Options.pdf


A New Approach for American Option Pricing: The Dynamic Chebyshev Method
+ https://epubs.siam.org/doi/10.1137/18M1193001


Efficient pricing of Bermudan options using recombining quadratures

+ https://yonsei.pure.elsevier.com/en/publications/efficient-pricing-of-bermudan-options-using-recombining-quadratur

Pricing options on flow forwards by neural networks in Hilbert space (2022)
https://arxiv.org/abs/2202.11606
https://www.youtube.com/watch?v=jOye0mznjqc



Projection of Functionals and Fast Pricing of Exotic Options
https://arxiv.org/abs/2111.03713


Gradient Boosting for Quantitative Finance
+ https://staff.fnwi.uva.nl/p.j.c.spreij/winterschool/19ReynersPaper.pdf

Use of Kernel Methods for Dynamic Hedging Incomplete Markets 
+ https://www.imperial.ac.uk/media/imperial-college/faculty-of-natural-sciences/department-of-mathematics/math-finance/Tang-Xiaofu_01904015.pdf

CodPy: A Python Library for Machine Learning, Mathematical Finance, and Statistics (RKHS)
+ https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4077158

**Dynamically Controlled Kernel Estimation for XVA Pricing and Options Replication**
+ https://www.imperial.ac.uk/media/imperial-college/faculty-of-natural-sciences/department-of-mathematics/math-finance/Qingxin_Geng_Thesis.pdf

Machine Learning for Quantitative Finance: Fast Derivative Pricing, Hedging and Fitting
+ Gaussian Process
+ https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3191050