---
title: "R Notebook"
output: html_notebook
---
## Neural PDEs

+ Sirignano Deep PDEs DGM: A deep learning algorithm for solving partial differential equations https://arxiv.org/abs/1708.07469
+ Neural Q-learning for solving elliptic PDEs (2022) https://arxiv.org/abs/2203.17128
+ The Deep Parametric PDE Method: Application to Option Pricing https://arxiv.org/pdf/2012.06211.pdf https://github.com/LWunderlich/DeepPDE/blob/main/TwoAssetsExample/DeepParametricPDEExample.ipynb
+ DNN Expression Rate Analysis of High-Dimensional PDEs: Application to Option Pricing https://link.springer.com/article/10.1007/s00365-021-09541-6
+ Physics-Informed Neural Networks and Option Pricing Andreas Louskos https://math.dartmouth.edu/theses/undergrad/2021/Louskos-thesis.pdf
+ Deep Learning of High-dimensional Partial Differential Equations
+ https://medium.com/data-analysis-center/solving-differential-equations-using-neural-networks-with-pydens-e831f1a115f


Solving high-dimensional partial differential equations using deep learning
+ https://github.com/frankhan91/DeepBSDE

Deep-learning based numerical BSDE method for barrier options
+ https://www.arxiv-vanity.com/papers/1904.05921/

Deep Learning-Based Algorithms for High-Dimensional PDEs and Control Problems
+ https://web.math.princeton.edu/~weinan/control.pdf

A new efficient approximation scheme for solving high-dimensional semilinear PDEs: control variate method for Deep BSDE solver
+ https://arxiv.org/abs/2101.09890

**Towards Robust and Stable Deep Learning Algorithms for Forward Backward Stochastic Differential Equations**
+ https://arxiv.org/abs/1910.11623
+ https://github.com/batuhanguler/Deep-BSDE-Solver


Deep Learning of High-dimensional Partial Differential Equations
+ https://www.imperial.ac.uk/media/imperial-college/faculty-of-engineering/computing/public/1819-pg-projects/Deep-Learning-of-High-dimensional-Partial-Differential-Equations.pdf


Neural Q-learning for solving elliptic PDEs
+ Samuel N. Cohen, Deqing Jiang, Justin Sirignano
+ https://arxiv.org/abs/2203.17128

Online Adjoint Methods for Optimization of PDEs
+  Justin Sirignano & Konstantinos Spiliopoulos 

PDE-constrained Models with Neural Network Terms: Optimization and Global Convergence
+ https://arxiv.org/abs/2105.08633

Scaling Limit of Neural Networks with the Xavier Initialization and Convergence to a Global Minimum
+ https://arxiv.org/abs/1907.04108

Deep splitting method for parabolic PDEs
+ https://arxiv.org/abs/1907.03452

Option Pricing by Neural Stochastic Differential Equations: A Simulation-Optimization Approach
+ https://ieeexplore.ieee.org/abstract/document/9715493?casa_token=4lhAPjJbRPsAAAAA:TBm6r04u-9zvxwjHPZGpKYZLIw63GH9JvbxCz4B0Sq0LOWHxlsxMVCLapKgzrX0VkOFS2zdgp6E

Neural Q-learning for solving elliptic PDEs
+ Samuel N. Cohen, Deqing Jiang, Justin Sirignano
+ https://arxiv.org/pdf/2203.17128.pdf
+ Arthur Jacot, Franck Gabriel, and Cl ́ement Hongler. Neural tangent ker-
nel: Convergence and generalization in neural networks. 


