---
title: "R Notebook"
output: html_notebook
---

## Neural Americans

Bernard Lapeyre, Jérôme Lelong. Neural network regression for Bermudan option pricing.
Monte Carlo Methods Appl. 27 (2021), no. 3, 227–247.

https://arxiv.org/pdf/1907.06474.pdf

2. Calypso Herrera, Florian Krach, Pierre Ruyssen, and Josef Teichmann, 2021. ”Optimal
Stopping via Randomized Neural Networks,” Papers 2104.13669, arXiv.org.
3. Becker, Sebastian; Cheridito, Patrick; Jentzen, Arnulf; Welti, Timo. Solving high-dimensional
optimal stopping problems using deep learning. European J. Appl. Math. 32 (2021), no. 3,
470–514. MR4253974 Add to clipboard
4. John Tsitsiklis and Benjamin Van Roy. Regression methods for pricing complex american-
style options. IEEE Transactions on Neural Networks, 12(4):694–703, 200

A new approach for American option pricing: The Dynamic Chebyshev method
https://arxiv.org/abs/1806.05579
https://www.youtube.com/watch?v=FWp1X8m5XX4

Machine Learning in Finance:
Applications of Continuous Depth
and Randomized Neural Networks
	


Optimal Stopping via Randomized Neural Networks
+ https://arxiv.org/pdf/2104.13669.pdf
https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/529739/3/thesis_calypso_herrera_20220128_withoutCV.pdf

## Bermudans
 
+ Bermudan Swaptions in Gaussian HJM One-Factor Model: Analytical and Numerical Approaches https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1287982
+ Pricing Bermudan Swaptions on the LIBOR Market Model
using the Stochastic Grid Bundling Method https://www.nag.com/doc/techrep/pdf/tr2_15.pdf
+ Evaluating Sensitivities of Bermudan Swaptions https://www.maths.ox.ac.uk/system/files/legacy/12804/Schlenkrich_20.3.11.pdf
+ https://arxiv.org/abs/2201.02587

Deep Learning-Based BSDE Solver for LiborMarket Model with Application to Bermudan Swaption Pricing and Hedging

+ https://www.cefpro.com/wp-content/uploads/2019/07/1807.06622.pdf

+ Valuation of Bermudan swaptions with a one-factor
Hull-White model https://essay.utwente.nl/61747/1/MSc_P_Nikolopoulos.pdf

+ Pricing and Hedging American-Style Options with Deep Learning https://mdpi-res.com/d_attachment/jrfm/jrfm-13-00158/article_deploy/jrfm-13-00158-v2.pdf?version=1595308716

+ Deep Optimal Stopping https://jmlr.org/papers/volume20/18-232/18-232.pdf

+ Learning Bermudans https://arxiv.org/abs/2105.00655	

**Generative Bayesian neural network model for risk-neutral pricing of American index options**

+ https://www.tandfonline.com/doi/full/10.1080/14697688.2018.1490807

### Bermudan Swaptions

The Swap Market Model with Local Stochastic Volatility
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2912558


The Co-Terminal Swap Market Model with Bergomi Stochastic Volatility
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3237914


Solving high-dimensional optimal stopping problems using deep learning
+ https://www.cambridge.org/core/journals/european-journal-of-applied-mathematics/article/solving-highdimensional-optimastopping-problems-using-deep-learning/A632772461C859353E6F8A7DAB8A1769
