name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'black[jupyter]'
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - uses: actions/checkout@v2
      - uses: psf/black@stable